apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    app: manifoldcf-db
  name: manifoldcf-db
spec:
  serviceName: manifoldcf-db-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: manifoldcf-db
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: "man1f0ldcf!"
        - name: POSTGRES_USER
          value: manifoldcf
        - name: PGDATA
          value: /var/lib/postgresql/data/manifoldcf
        image: postgres:9.6.14
        name: manifoldcf-db
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: manifoldcf-db-vol
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: manifoldcf-db-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: manifoldcf-db
  name: manifoldcf-db-svc
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    app: manifoldcf-db
