apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    app: manifoldcf-db-replica
  name: manifoldcf-db-replica
spec:
  serviceName: manifoldcf-db-replica
  replicas: 1
  template:
    metadata:
      labels:
        app: manifoldcf-db-replica
    spec:
      containers:
      - env:
        - name: POSTGRESQL_MASTER_SERVICE_NAME
          value: manifoldcf-db
        - name: POSTGRESQL_MASTER_USER
          value: dbmaster
        - name: POSTGRESQL_MASTER_PASSWORD
          value: "dbmaster"
        - name: POSTGRESQL_DATABASE
          value: manifoldcf
        - name: POSTGRESQL_USER
          value: manifoldcf
        - name: POSTGRESQL_PASSWORD
          value: "man1f0ldcf!"
        image: registry.access.redhat.com/rhscl/postgresql-96-rhel7
        name: manifoldcf-db-replica
        args:
          - run-postgresql-slave
        ports:
        - containerPort: 5432
        readinessProbe:
          timeoutSeconds: 1
          initialDelaySeconds: 5
          exec:
            command:
            - "/usr/libexec/check-container"
        livenessProbe:
          timeoutSeconds: 10
          initialDelaySeconds: 120
          exec:
            command:
            - "/usr/libexec/check-container"
            - "--live"
        resources: {}
        volumeMounts:
        - mountPath: /opt/app-root/src/postgresql-cfg/postgres.conf
          name: postgresql-config-vol
          subPath: postgres.conf
        - mountPath: /var/lib/pgsql/data
          name: manifoldcf-db-replica-vol
      restartPolicy: Always
      volumes:
        - name: postgresql-config-vol
          configMap:
            name: postgresql-config
  volumeClaimTemplates:
  - metadata:
      name: manifoldcf-db-replica-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: manifoldcf-db-replica
  name: manifoldcf-db-replica
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    app: manifoldcf-db-replica
