apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    app: manifoldcf-db
  name: manifoldcf-db
spec:
  serviceName: manifoldcf-db-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: manifoldcf-db
    spec:
      containers:
      - env:
        - name: POSTGRESQL_DATABASE
          value: manifoldcf
        - name: POSTGRESQL_USER
          value: manifoldcf
        - name: POSTGRESQL_PASSWORD
          value: "man1f0ldcf!"
        image: registry.access.redhat.com/rhscl/postgresql-96-rhel7
        name: manifoldcf-db
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /opt/app-root/src
          name: postgresql-config-vol
        - mountPath: /var/lib/pgsql/data
          name: manifoldcf-db-vol
      restartPolicy: Always
      volumes:
        - name: postgresql-config-vol
          configMap:
            name: postgresql-config
  volumeClaimTemplates:
  - metadata:
      name: manifoldcf-db-vol
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: manifoldcf-db
  name: manifoldcf-db-svc
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    app: manifoldcf-db
