apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: manifoldcf-web
  name: manifoldcf-web-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: manifoldcf-web
  name: manifoldcf-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: manifoldcf-web
    spec:
      containers:
      - env:
        - name: POSTGRES_HOSTNAME
          value: manifoldcf-db-svc
        - name: POSTGRES_PASSWORD
          value: "man1f0ldcf!"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_SSL
          value: "false"
        image: perficientdevops/manifoldcf:2.11
        name: manifoldcf-web
        ports:
        - containerPort: 8345
        resources: {}
        volumeMounts:
        - mountPath: /var/manifoldcf
          name: manifoldcf-web-vol
      restartPolicy: Always
      volumes:
      - name: manifoldcf-web-vol
        persistentVolumeClaim:
          claimName: manifoldcf-web-claim
---
apiVersion: v1
kind: Service
metadata:
  name: manifoldcf-web-svc
spec:
  ports:
  - port: 8345
    protocol: TCP
    targetPort: 8345
  selector:
    app: manifoldcf-web
  type: NodePort
